version: '2.1'

services:
    sb-actuator-service:
        build:
            dockerfile: Dockerfile
            context: ./sb-actuator-service
        image: sb-actuator-service
        ports:
            - 9000:9000
            - 9010:9010
        container_name: sb-actuator-service
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
          timeout: 30s
    mocha-load-test:
        image: node
        links:
          - sb-actuator-service
        container_name: mocha-load-test
        depends_on:
          - sb-actuator-service
        volumes:
          - ./test-load/:/src
        environment:
          - DEBUG=*
          - SERVICE_HOST=sb-actuator-service
        working_dir: /src
        command: ["./runTest.sh"]
